// One shared curriculum; each language receives its own starter syntax.
const rows = [
[1,'Array sum','Arrays','Return the sum of all numbers. An empty array has sum zero.','[2,4,6,8]','20','Keep a running total.'],
[1,'Largest number','Arrays','Return the largest value in a nonempty integer array.','[-4,7,2,7]','7','Initialize from the first element.'],
[1,'Smallest number','Arrays','Return the smallest value in a nonempty integer array.','[8,-2,5]','-2','Compare each value with the current minimum.'],
[1,'Even counter','Loops','Count the even integers, including zero and negative even values.','[0,1,2,3,-4]','3','Check remainder after division by two.'],
[1,'Reverse an array','Arrays','Return the elements in reverse order without using a built-in reverse operation.','[1,2,3,4]','[4,3,2,1]','Swap values from the two ends.'],
[1,'Linear search','Search','Return the first index of the target, or -1 if absent.','array=[4,8,4], target=4','0','Scan from left to right.'],
[1,'Count occurrences','Arrays','Count how many times the target appears.','array=[2,1,2,2], target=2','3','Increment only on a match.'],
[1,'Second distinct maximum','Arrays','Return the second-largest distinct value, or null if it does not exist.','[9,9,3,7]','7','Track two different maxima.'],
[1,'Ascending order check','Arrays','Return true if the array is nondecreasing; an empty array is sorted.','[1,2,2,5]','true','Compare neighboring values.'],
[1,'Prefix totals','Arrays','Return an array where position i is the sum through index i.','[2,4,1]','[2,6,7]','Reuse the previous total.'],
[1,'Factorial','Functions','Return n factorial for 0 <= n <= 10. Define 0 factorial as 1.','n=5','120','Multiply integers from 1 through n.'],
[1,'Fibonacci number','Loops','Return F(n), with F(0)=0 and F(1)=1, for 0 <= n <= 20.','n=7','13','Track the previous two values.'],
[1,'Digit sum','Numbers','Return the sum of decimal digits of a nonnegative integer.','n=2045','11','Repeatedly extract the last digit.'],
[1,'Prime check','Numbers','Determine whether an integer n >= 0 is prime.','n=29','true','Check divisors while divisor squared is at most n.'],
[1,'Greatest common divisor','Numbers','Return the GCD of two nonnegative integers, not both zero.','a=48, b=18','6','Use repeated remainders.'],
[1,'Reverse a string','Strings','Reverse a string of ASCII characters without a built-in reverse operation.','"trace"','"ecart"','Read characters from the final index.'],
[1,'Palindrome check','Strings','Check whether an ASCII string reads the same backward; comparison is case-sensitive.','"level"','true','Compare matching positions from both ends.'],
[1,'Vowel counter','Strings','Count English vowels in an ASCII string, ignoring case.','"Tracecode"','4','Compare each character against a, e, i, o, u.'],
[1,'Grade summary','Mini project','Given scores from 0 to 100, return their sum and how many are at least 40.','[35,60,80]','sum=175, passed=2','Maintain independent counters.'],
[1,'Shopping receipt','Mini project','Given item prices in cents and matching quantities, compute the total in cents.','prices=[250,100], quantities=[2,3]','800','Multiply each price by its quantity before adding.'],
[2,'Binary search','Search','Find a target index in a strictly increasing array, or return -1.','array=[1,3,5,7,9], target=7','3','Halve the remaining search range.'],
[2,'Lower bound','Search','Return the first index with value at least target, or the array length. Input is sorted.','array=[1,3,3,8], target=3','1','Keep the leftmost valid candidate.'],
[2,'Two sum','Hashing','Return indices of two different elements that sum to target. Exactly one pair exists.','array=[2,7,11,15], target=9','[0,1]','Remember previously seen values.'],
[2,'Move zeros','Arrays','Move zeros to the end while preserving nonzero order.','[0,1,0,3,12]','[1,3,12,0,0]','Use a write pointer for nonzero values.'],
[2,'Rotate right','Arrays','Rotate an array right by k positions; k is nonnegative.','array=[1,2,3,4,5], k=2','[4,5,1,2,3]','Reduce k modulo the length for nonempty arrays.'],
[2,'Merge sorted arrays','Arrays','Merge two sorted arrays into a single nondecreasing array.','a=[1,4], b=[2,3,5]','[1,2,3,4,5]','Use one pointer for each input.'],
[2,'Remove sorted duplicates','Arrays','Return distinct values from a sorted array, in order.','[1,1,2,3,3]','[1,2,3]','Compare with the most recently kept value.'],
[2,'Maximum subarray','Dynamic programming','Return the largest sum of a nonempty contiguous subarray.','[-2,1,-3,4,-1,2,1,-5,4]','6','Decide whether to extend or restart at each index.'],
[2,'Fixed window maximum sum','Sliding window','Return the largest sum of any k consecutive elements; 1 <= k <= length.','array=[2,1,5,1,3,2], k=3','9','Add the new value and subtract the outgoing value.'],
[2,'Balanced brackets','Stacks','Validate a string containing only (), [] and {} brackets.','"{[()]}"','true','Push openers and match closing brackets.'],
[2,'Next greater element','Stacks','For each value, return the next strictly greater value to its right, or -1.','[2,1,2,4,3]','[4,2,4,-1,-1]','Maintain a monotonic stack of unresolved positions.'],
[2,'Merge intervals','Sorting','Merge overlapping closed intervals and return them ordered by start.','[[1,3],[2,6],[8,10]]','[[1,6],[8,10]]','Sort by start before merging.'],
[2,'Anagram check','Strings','Determine if two lowercase English strings contain the same character counts.','a="listen", b="silent"','true','Use 26 counters.'],
[2,'First unique character','Strings','Return the index of the first character occurring once, or -1. Input is lowercase English.','"leetcode"','0','Count first, then scan in original order.'],
[2,'Longest distinct substring','Sliding window','Return the length of the longest ASCII substring without repeated characters.','"abcabcbb"','3','Move the left edge past a repeated character.'],
[2,'Matrix transpose','Matrices','Return the transpose of a nonempty rectangular matrix.','[[1,2,3],[4,5,6]]','[[1,4],[2,5],[3,6]]','Exchange row and column positions.'],
[2,'Flood fill','Graphs','Replace a four-connected region of the starting color with a new color.','grid=[[1,1],[1,0]], start=[0,0], color=2','[[2,2],[2,0]]','Traverse only adjacent cells of the original color.'],
[2,'Recursive subsets','Backtracking','Return every subset of distinct integers; order does not matter.','[1,2]','[[],[1],[2],[1,2]]','Choose whether to include each value.'],
[2,'Inventory tracker','Mini project','Start with zero stock; process signed stock adjustments and return final counts. Assume stock never goes negative.','[("pen",5),("book",2),("pen",-3)]','pen=2, book=2','Store one count per product.'],
[2,'Undoable counter','Mini project','Start at zero. Apply add(n) commands; undo removes the most recent non-undone add. Empty undo does nothing.','add(5), add(3), undo, add(2)','7','Save previous states in a stack.'],
[3,'Trapping rain water','Two pointers','Calculate water trapped between bars of width one and nonnegative heights.','[4,2,0,3,2,5]','9','The shorter boundary determines the next safe step.'],
[3,'Largest histogram rectangle','Stacks','Find the largest rectangle area in a histogram of nonnegative heights and unit bar widths.','[2,1,5,6,2,3]','10','A monotonic stack finds each height boundary.'],
[3,'Sliding window maximum','Sliding window','Return the maximum in every consecutive window of size k.','array=[1,3,-1,-3,5,3,6,7], k=3','[3,3,5,5,6,7]','Keep useful indices in a decreasing deque.'],
[3,'Median of sorted arrays','Binary search','Find the median of two sorted arrays whose combined length is positive.','a=[1,3], b=[2]','2','Partition the shorter array.'],
[3,'Merge sort','Sorting','Sort an integer array using merge sort and return the result.','[5,2,4,1,3]','[1,2,3,4,5]','Split, recursively sort and merge.'],
[3,'Kth largest','Selection','Return the kth largest element, counting duplicates; 1 <= k <= length.','array=[3,2,1,5,6,4], k=2','5','Use partitioning or a size-k min heap.'],
[3,'Longest increasing subsequence','Dynamic programming','Return the length of the longest strictly increasing subsequence.','[10,9,2,5,3,7,101,18]','4','Track best lengths, or the smallest tail for each length.'],
[3,'Minimum coin change','Dynamic programming','Return the fewest coins needed for an amount, or -1 if impossible. Positive denominations may be reused.','coins=[1,2,5], amount=11','3','Build optimal answers for smaller amounts.'],
[3,'Edit distance','Dynamic programming','Find the minimum insertions, deletions and substitutions to transform one ASCII string into another.','a="horse", b="ros"','3','Compare prefixes in a two-dimensional table.'],
[3,'Zero-one knapsack','Dynamic programming','Maximize value under a weight limit; each item may be selected once.','weights=[1,3,4], values=[15,20,30], capacity=4','35','Compare taking and skipping each item.'],
[3,'N-Queens count','Backtracking','Count placements of n queens with no shared row, column or diagonal; 1 <= n <= 8.','n=4','2','Place one queen per row and track occupied diagonals.'],
[3,'Word search','Backtracking','Determine if a word can be formed in a character grid via four-way moves without reusing a cell.','grid=[[A,B],[C,D]], word="ABD"','true','Mark visited cells during each candidate path.'],
[3,'Shortest unweighted path','Graphs','Return shortest edge distance between two vertices of an undirected graph, or -1.','edges=[[0,1],[1,2],[0,3],[3,2]], source=0, target=2','2','Use breadth-first search.'],
[3,'Topological ordering','Graphs','Return any valid ordering of a directed acyclic graph. Include all vertices from 0 to n-1.','n=4, edges=[[0,1],[0,2],[1,3],[2,3]]','[0,1,2,3] or [0,2,1,3]','Process vertices with zero incoming edges.'],
[3,'Dijkstra distances','Graphs','Return shortest distances from source in a directed graph with nonnegative edge weights. Use null for unreachable vertices.','n=3, edges=[[0,1,4],[0,2,1],[2,1,2]], source=0','[0,3,1]','Relax edges using the smallest tentative distance.'],
[3,'Connected components','Graphs','Count connected components in an undirected graph, including isolated vertices.','n=5, edges=[[0,1],[1,2],[3,4]]','2','Visit each unseen vertex or use disjoint sets.'],
[3,'LRU cache','Mini project','Implement get and put with a capacity limit. Missing get returns -1; accessed or updated keys become most recent.','capacity=2; put(1,10), put(2,20), get(1), put(3,30), get(2)','get results=[10,-1]','Combine a map with an ordered doubly linked list.'],
[3,'Prefix search index','Mini project','Store lowercase words in a trie and return all matching words for a prefix in alphabetical order.','words=["car","cat","dog"], prefix="ca"','["car","cat"]','Locate the prefix node, then traverse its descendants.'],
[3,'Task dependency planner','Mini project','Return the minimum parallel rounds to finish unit-duration tasks with prerequisites; return -1 for a cycle.','tasks=[A,B,C,D], prerequisites=[A→C,B→C,C→D]','3','Process each zero-indegree layer as one round.'],
[3,'Expression evaluator','Mini project','Evaluate integers with +, -, *, / and parentheses. Division truncates toward zero; input has no unary operators or zero divisors.','"(2 + 3) * 4 - 6 / 2"','17','Respect precedence using stacks or a parser.']
];
export const exercises=rows.map(([level,title,topic,question,input,expected,hint],i)=>({id:'exercise-'+String(i+1).padStart(2,'0'),level,title,topic,question,input,expected,hint}));
export function starterFor(exercise,language){
 const mark=language==='Python'?'#':'//';
 const header=[exercise.title,'Level '+exercise.level+' · '+exercise.topic,exercise.question,'Sample input: '+exercise.input,'Expected result: '+exercise.expected,'TODO: implement the solution. This is a starter, not a completed example.'].map(s=>mark+' '+s).join('\n');
 const templates={
 JavaScript:'function solve(input) {\n  // Write your solution here.\n}\n\n// Set input from the question, then call console.log(solve(input)).',
 TypeScript:'function solve(input: unknown): unknown {\n  // Replace unknown with the appropriate input/output types.\n  throw new Error("Not implemented");\n}',
 Python:'def solve(data):\n    # Write your solution here.\n    raise NotImplementedError("Write your solution")\n\n# Set data from the question, then print(solve(data)).',
 Java:'public class Main {\n    public static void main(String[] args) {\n        // Define input and implement the solution here.\n    }\n}',
 C:'#include <stdio.h>\n\nint main(void) {\n    // Define input and implement the solution here.\n    return 0;\n}',
 'C++':'#include <iostream>\n#include <vector>\n\nint main() {\n    // Define input and implement the solution here.\n    return 0;\n}',
 Go:'package main\n\nfunc main() {\n    // Define input and implement the solution here.\n}',
 Rust:'fn main() {\n    // Define input and implement the solution here.\n}',
 Kotlin:'fun main() {\n    // Define input and implement the solution here.\n}',
 Swift:'import Foundation\n\n// Define input and implement the solution here.'
 };
 if(!templates[language])throw Error('Unknown language');return header+'\n\n'+templates[language]+'\n';
}
